import React,{useEffect,useRef,useState} from 'react';
import {service} from '../services/api';
type SpeechResult={results:ArrayLike<ArrayLike<{transcript:string}>>};
type Recognition={lang:string;continuous:boolean;interimResults:boolean;onresult:((e:SpeechResult)=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};
export default function VoiceNote({onTranscript}:{onTranscript:(text:string)=>void}){
 const [consent,setConsent]=useState(false),[recording,setRecording]=useState(false),[dictating,setDictating]=useState(false),[url,setUrl]=useState(''),[blob,setBlob]=useState<Blob|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),recognition=useRef<Recognition|null>(null),timer=useRef<ReturnType<typeof setTimeout>>();
 useEffect(()=>()=>{recognition.current?.abort();if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());clearTimeout(timer.current);},[]);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url);},[url]);
 function acceptAudio(audio:Blob){if(audio.size>10*1024*1024){setError('Choose an audio note smaller than 10 MB.');return;}setBlob(audio);setUrl(URL.createObjectURL(audio));setError('');}
 async function record(){setError('');try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream.current);recorder.current=r;const chunks:BlobPart[]=[];r.ondataavailable=e=>chunks.push(e.data);r.onstop=()=>{acceptAudio(new Blob(chunks,{type:r.mimeType}));stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);clearTimeout(timer.current);};r.start();setRecording(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop();},60000);}catch{setError('Microphone access was unavailable. You can upload a note or type instead.');}}
 function dictate(){const w=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const Constructor=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Constructor){setError('Browser dictation is not supported here. Record or upload a note and type its transcript.');return;}const r=new Constructor();recognition.current=r;r.lang='en-IN';r.continuous=false;r.interimResults=false;r.onresult=e=>onTranscript(Array.from(e.results).map(row=>row[0].transcript).join(' '));r.onerror=e=>{setError('Dictation unavailable: '+e.error+'. You can type instead.');setDictating(false);};r.onend=()=>setDictating(false);try{r.start();setDictating(true);}catch{setError('Could not start dictation.');}}
 return <div className="voice-panel"><label className="check-row"><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);if(!e.target.checked){recognition.current?.abort();if(recorder.current?.state==='recording')recorder.current.stop();}}}/>I choose to use my microphone. Browser dictation may send audio to my browser provider; local recordings stay in memory.</label><div className="voice-actions"><button className={recording?'secondary recording':'secondary'} disabled={!consent||dictating} onClick={()=>recording?recorder.current?.stop():void record()}>{recording?'■ Stop recording':'○ Record voice note'}</button><button className="secondary" disabled={!consent||recording} onClick={()=>dictating?recognition.current?.stop():dictate()}>{dictating?'Stop dictation':'Use browser speech-to-text'}</button><label className="upload-control">Upload audio<input type="file" accept="audio/*" onChange={e=>{const f=e.target.files?.[0];if(f){if(!f.type.startsWith('audio/'))setError('Choose an audio file.');else acceptAudio(f);}}}/></label></div><small>Up to 60 seconds when recording · 10 MB upload limit · Review the transcript before analysis.</small>{url&&<div className="audio-preview"><audio controls src={url}/><button className="text-action" onClick={()=>{setUrl('');setBlob(null);}}>Delete recording</button><button className="secondary" disabled={busy} onClick={async()=>{if(!blob)return;setBusy(true);try{onTranscript(await service.transcribe(blob));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Transcribe uploaded note</button></div>}{error&&<p role="alert" className="error">{error}</p>}</div>;
}
